# 1. Create a 3x3x3 array with random values

In [1]:
import numpy as np
randomArr= np.random.randint(1,999,size=(3,3,3))

randomArr

array([[[783, 668, 380],
        [634, 699, 747],
        [327, 285, 851]],

       [[256, 203, 802],
        [700,  67, 677],
        [ 89, 628, 498]],

       [[411, 151, 844],
        [978,  18, 281],
        [207, 866,  95]]])

# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
arr=np.diag([1,2,3,4], -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
arr=np.zeros((8,8))
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [4]:
arr1=np.random.random((5,5))
print("Original array is \n",arr1)
from sklearn.preprocessing import normalize
arr2=normalize(arr1)
print("Normalised array is \n",arr2)

Original array is 
 [[0.29185111 0.37905552 0.1883081  0.59187638 0.48480546]
 [0.09315297 0.13389073 0.5680391  0.10479074 0.65462846]
 [0.26743852 0.16181082 0.72096549 0.67784804 0.25280638]
 [0.00769267 0.14202833 0.04012104 0.3207353  0.82222474]
 [0.61067225 0.14399867 0.71357521 0.09560134 0.30784489]]
Normalised array is 
 [[0.31661768 0.41122229 0.20428798 0.64210318 0.5259462 ]
 [0.10488549 0.15075413 0.63958304 0.11798903 0.73707825]
 [0.25038181 0.15149083 0.67498369 0.63461619 0.23668287]
 [0.00859656 0.15871657 0.04483524 0.3584215  0.91883566]
 [0.60862043 0.14351484 0.71117764 0.09528013 0.30681055]]


# 5. How to find common values between two arrays?

In [6]:
arr3=np.array([10,20,30,40,60])
print("First array is \n",arr3)
arr4=np.array([20,40,60,80,100])
print("Second  array is \n",arr4)
comarr=np.intersect1d (arr3, arr4)
print("Common elements are ",comarr)

First array is 
 [10 20 30 40 60]
Second  array is 
 [ 20  40  60  80 100]
Common elements are  [20 40 60]


# 6.How to get the dates of yesterday, today and tomorrow?

In [7]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-29
Today:  2020-07-30
Tomorrow:  2020-07-31


# 7. Consider two random array A and B, check if they are equal

In [8]:
randomArr1= np.random.randint(1,10,size=(2,2))
print("First array is\n",randomArr1)
randomArr2= np.random.randint(1,10,size=(2,2))
print("Second array is\n",randomArr2)
if ((randomArr1==randomArr2).all()==True):
    print("Equal ")
else:
    print("Not equal ")

First array is
 [[5 6]
 [5 4]]
Second array is
 [[2 6]
 [6 8]]
Not equal 


# 8.Create random vector of size 10 and replace the maximum value by 0

In [9]:
print("Random vector of size 10:\n")
vect= np.random.randint(1,50, size = 10)
print(vect)
vect[vect.argmax()]=0
print("Vector after replacing the max value to 0 :\n",vect)

Random vector of size 10:

[35 39  8 46  7  8 32 38 45 20]
Vector after replacing the max value to 0 :
 [35 39  8  0  7  8 32 38 45 20]


# 9. How to print all the values of an array?

In [10]:
arr5 = np.arange(51)
np.set_printoptions(threshold=np.inf)
print(arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


# 10.Subtract the mean of each row of a matrix

In [11]:
print("Original matrix:\n")
arr6= np.random.randint(1,5,size=(3,4))
print(arr6)
print("\nSubtract the mean of each row of the matrix:\n")
arr7 = arr6-arr6.mean(axis=1, keepdims = True)
print(arr7)

Original matrix:

[[2 1 2 4]
 [2 2 1 1]
 [3 3 2 1]]

Subtract the mean of each row of the matrix:

[[-0.25 -1.25 -0.25  1.75]
 [ 0.5   0.5  -0.5  -0.5 ]
 [ 0.75  0.75 -0.25 -1.25]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
a = np.random.randint(1,8,8)
print("Given vector:", a)
b = np.random.randint(a)
c = []
b.sort()
for i in b:
    if i not in c:
        c.append(i)

for j in c:
    a[j] += 1

print("Indexing vector:", b)
print("Result:",a)

Given vector: [6 7 2 2 5 5 2 6]
Indexing vector: [0 1 1 1 1 3 3 5]
Result: [7 8 2 3 5 6 2 6]


# 12.How to get the diagonal of a dot product?

In [13]:
x= [[1,2],[3,4]]
y = [[5,6],[7,8]]
z = np.diag(np.dot(x,y))
z

array([19, 50])

# 13.How to find the most frequent value in an array?

In [14]:
arr8= np.random.randint(0, 100, 30)
print("Original array:")
print(arr8)
print("Most frequent value in the above array:")
print(np.bincount(arr8).argmax())

Original array:
[55 49 21 75  7  3 93  0 67 96  7 26 38 69 29 56 89 54 13 26 49  7 40 87
 66 96 37 19 35 56]
Most frequent value in the above array:
7


# 14.How to get the n largest values of an array

In [15]:
x = np.arange(99)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]
[98]


# 15.How to create a record array from a regular array?

In [16]:
a1=np.array(['Veggie','Tomatoes','Chilli ','Carrot','Lemon'])
a2=np.array(['color','Red','Green','Orange','Yellow'])
result= np.core.records.fromarrays([a1, a2])
print(result[0])
print(result[1])
print(result[2])
print(result[3])
print(result[4])

('Veggie', 'color')
('Tomatoes', 'Red')
('Chilli ', 'Green')
('Carrot', 'Orange')
('Lemon', 'Yellow')
